version: '3.8'

services:
  backend:
    build: .
    container_name: eterna-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PORT=3000
    restart: always

  worker:
    build: .
    container_name: eterna-worker
    command: npm run start:worker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    restart: always
